api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
	
	path('voter-detail/<int:pk>/', views.voter_detail, name='voter-detail'),
	path('voter-react/', views.voter, name='voter-react' ),
	path('voter-create/', views.voter_react_create, name='create-voter'),
	path('vote-register/', views.vote_register, name='vote-register'),
	path('verifier/email/<str:email>', views.get_email_verify, name='email-verifier'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from accounts.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', TemplateView.as_view(template_name='homepage.html'), name='home'),
    path('', include('memail.urls')),
    path('', include('upstaged_data.urls')),

    path('', include('dashboard.urls')),
    path('', include('contacts.urls')),
    path('api-v1/', include('api.urls')),


    # path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

upstaged_data/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from upstaged_data.views import (
    EmailUpload, 
    VoterList, 
    send_email_confirmation, 
    VerifiedEmailList, 
    DateWiseEmailList, 
    DataSheetUpload, 
    PendingEmailList,
    InvalidEmailList,
    DataSheetListView,
    load_unique_emails,
    IsEmailSendList,
    IPAddressList,
    ip_address_list,
    link_voter_datasheet,
    send_bulk_email_confirmation,
    IPVoterList,
    export_voters_data,
    IPVoterAction,
    DuplicateDataSheetFind,
    DuplicateVoteList,
    export_dulicate_entry,
    TempIPAddressList,
    TempIPVoterAction,
    TempIPVoterList,
    make_invalid_action_for_ip_voters,
)


app_name = 'upstaged_data'

urlpatterns = [

    path('data-sheet/upload/', login_required(DataSheetUpload.as_view()), name="data-sheet-upload"),
    path('data-sheet/upload/duplicate/', login_required(DuplicateDataSheetFind.as_view()), name="find-duplicates"),

    path('data-sheet/email/load/', login_required(load_unique_emails), name="email-load"),
    path('data-sheet/email/bulk-send/', login_required(send_bulk_email_confirmation), name="send_bulk-email"),


    path('data-sheet/email/load/', login_required(link_voter_datasheet), name="link-voter-datasheet"),

    path('voter/duplicate/votes/', login_required(DuplicateVoteList.as_view()), name='duplicate-vote-list'),
    path('voter/duplicate/votes/export/', login_required(export_dulicate_entry), name='export-duplicate-vote-list'),

    path('voter/', login_required(VoterList.as_view()), name='unique-emails'),
    path('voter/verified/', login_required(VerifiedEmailList.as_view()), name='all-verified-emails'),
    path('voter/pending/', login_required(PendingEmailList.as_view()), name='all-pending-emails'),
    path('voter/invalid/', login_required(InvalidEmailList.as_view()), name='all-invalid-emails'),
    path('voter/verification/email/', login_required(IsEmailSendList.as_view()), name='verification-emails-list'),

    path('voter/ip-address/', login_required(IPAddressList.as_view()), name='ip-address-list'),
    path('voter/ip-address/voter/', login_required(IPVoterList.as_view()), name='ip-address-voters'),
    path('voter/ip-address/voter/action/', login_required(IPVoterAction.as_view()), name='ip-voters-action'),

    path('voter/ip-address/test/', login_required(TempIPAddressList.as_view()), name='temp-ip-address-list'),
    path('voter/ip-address/voter/test/', login_required(TempIPVoterList.as_view()), name='temp-ip-address-voters'),
    path('voter/ip-address/voter/action/test/', login_required(TempIPVoterAction.as_view()), name='temp-ip-voters-action'),
    path('voter/ip-address/voter/action/test/invalid/', login_required(make_invalid_action_for_ip_voters), name='make-invalid-ip-voter'),





    path('voter/export/', login_required(export_voters_data), name='export-voters'),

    # path('email/voter/ip-address/', ip_address_list, name='ip-address-list'),

    path('data-sheet/', login_required(DataSheetListView.as_view()), name='data-sheet'),

    path('email/user/date/', login_required(DateWiseEmailList.as_view()), name='date-wise-emails'),
    path('send-email-confirmation-link/<int:pk>/', login_required(send_email_confirmation), name='send_email_cnfrm'),



]

upstaged_data/views.py
import csv, io
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse

from django.views.generic import FormView, ListView
# Create your views here.
# one parameter named request
from upstaged_data.models import  Voter, Datasheet, TempDatasheet, DuplicateVotes, TempVoter
from accounts.views import send_email_confirmation_link

from datetime import datetime
from django.utils.timezone import make_aware
from django.db.models import Count
from upstaged_data.resources import VoterResource
from django.db import connection

class EmailUpload(FormView):

    def get(self, request, *args, **kwargs):
        """
        docstring
        """
        return render(request, 'upstaged_data/emails_upload.html')

    def post(self, request, *args, **kwargs):
        """
        docstring
        """
        csv_file = request.FILES['file']
        # let's check if it is a csv file
        
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'THIS IS NOT A CSV FILE')  

        data_set = csv_file.read().decode('UTF-8')
        # setup a stream which is when we loop through each line we are able to handle a data in a stream
        io_string = io.StringIO(data_set)
        next(io_string)
        count = 0


        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            count = count + 1
            str_date = column[7].strip('GMT+0000 (Coordinated Universal Time)')

            try:
                # str_date = "Nov 23 2020 16:19:41" # example
                date_time_obj = datetime.strptime(str_date, "%b %d %Y %H:%M:%S")
                # date_time_obj = "2012-09-04 06:00Z" # example
            except ValueError as e:
                date_time_obj = datetime.strptime(str_date, "%b %d %Y %H:%M:")

            _, created = Voter.objects.update_or_create(
                name=column[0],
                email=column[1],
                vote_time=date_time_obj,
            )
            print(count)

        messages.warning(request, 'message from post function')
        return render(request, 'upstaged_data/emails_upload.html')


# Data Sheet upload - form
class DataSheetUpload(FormView):

    def get(self, request, *args, **kwargs):
        return render(request, 'upstaged_data/data_sheet_upload.html')

    def post(self, request, *args, **kwargs):
        """
        docstring
        """
        csv_file = request.FILES['file']
        # let's check if it is a csv file
        
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'THIS IS NOT A CSV FILE')  

        data_set = csv_file.read().decode('UTF-8')
        # setup a stream which is when we loop through each line we are able to handle a data in a stream
        io_string = io.StringIO(data_set)
        next(io_string)
        create_count = 0
        skip_count = 0
        fake_entry = []
        for column in csv.reader(io_string, delimiter=',', quotechar="|"): 
            if not Datasheet.objects.filter(email=column[1].strip(), game=column[5].strip()).exists():
                Datasheet.objects.create(
                    name = column[0].strip(),
                    email = column[1].strip(),
                    ip_address = column[2].strip(),
                    group = column[3].strip(),
                    round = column[4].strip(),
                    game = column[5].strip(),
                    voted_for = column[6].strip(),
                    vote_time = column[7].strip(),
                )
                create_count = create_count + 1
                # print(create_count)
            else:
                skip_count = skip_count + 1
                # print(skip_count)

        # print(create_count)
        # print(skip_count)
        messages.warning(request, 'message from post function')
        return render(request, 'upstaged_data/data_sheet_upload.html')


# Data Sheet upload - form - find duplicate entry
class DuplicateDataSheetFind(FormView):
    def get(self, request, *args, **kwargs):
        return render(request, 'upstaged_data/duplicate_votes_list.html')
    
    def post(self, request, *args, **kwargs):
        csv_file = request.FILES['file']
        # let's check if it is a csv file
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'THIS IS NOT A CSV FILE')  
        data_set = csv_file.read().decode('UTF-8')
        # setup a stream which is when we loop through each line we are able to handle a data in a stream
        io_string = io.StringIO(data_set)
        next(io_string)
        create_count = 0
        fake_entry = []
        fake_entry_count = 0
        for column in csv.reader(io_string, delimiter=',', quotechar="|"): 
            if not TempDatasheet.objects.filter(email=column[1].strip(), game=column[5].strip()).exists():
                TempDatasheet.objects.create(
                    name = column[0].strip(),
                    email = column[1].strip(),
                    ip_address = column[2].strip(),
                    group = column[3].strip(),
                    round = column[4].strip(),
                    game = column[5].strip(),
                    voted_for = column[6].strip(),
                    vote_time = column[7].strip(),
                )
                create_count = create_count + 1
                # print(create_count)
            elif not DuplicateVotes.objects.filter(name=column[0].strip(), email=column[1].strip(), game=column[5].strip(), voted_for=column[6].strip()).exists():
                print(column[1])
                DuplicateVotes.objects.create(
                    name = column[0].strip(),
                    email = column[1].strip(),
                    ip_address = column[2].strip(),
                    group = column[3].strip(),
                    round = column[4].strip(),
                    game = column[5].strip(),
                    voted_for = column[6].strip(),
                    vote_time = column[7].strip(),               
                )
                fake_entry_count = fake_entry_count + 1
                # print(fake_entry_count)
            else:
                pass
        TempDatasheet.objects.all().delete()      
        # print(create_count)
        # print(fake_entry_count)
        return render(request, 'upstaged_data/duplicate_votes_list.html')


# script for finding duplicate entry from common ninja datasheet - clean entry from beginning to end
def export_dulicate_entry(request):

    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)

    #Header
    writer.writerow(['Name', 'Email', 'IP Address', 'Group', 'Round', 'Game', 'Voted For', 'Date'])
    obj_list = []
    res_list = DuplicateVotes.objects.all()
    for ob in res_list:
        obj_list.append([ob.name, ob.email, ob.ip_address, ob.group, ob.round, ob.game, ob.voted_for, ob.vote_time,])
    #CSV Data
    writer.writerows(obj_list)
    response['Content-Disposition'] = 'attachment; filename="fakevoters.csv"'
    return response

def export_all_invalid_voters(request):
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)

    #Header
    writer.writerow(['Name', 'Email', 'IP Address', 'Group', 'Round', 'Game', 'Voted For', 'Date'])
    obj_list = []
    res_list = DuplicateVotes.objects.all()
    for ob in res_list:
        obj_list.append([ob.name, ob.email, ob.ip_address, ob.group, ob.round, ob.game, ob.voted_for, ob.vote_time,])
    #CSV Data
    writer.writerows(obj_list)
    response['Content-Disposition'] = 'attachment; filename="fakevoters.csv"'
    return response

class DuplicateVoteList(ListView):
    model = DuplicateVotes
    paginate_by = 10

# Unique / Email Voter listing
class VoterList(ListView):
    model = Voter
    paginate_by = 10
    queryset = Voter.objects.all()


class VerifiedEmailList(ListView):
    model = Voter
    paginate_by = 10
    queryset = Voter.objects.filter(email_confirmed=True).order_by('email')


class PendingEmailList(ListView):
    model = Voter
    paginate_by = 10
    queryset = Voter.objects.filter(verification_pending=True, email_confirmed=False, invalid=False).order_by('email')

class IsEmailSendList(ListView):
    model = Voter
    paginate_by = 10
    queryset = Voter.objects.filter(verification_pending=True, email_confirmed=False, invalid=False, is_email_sent=False).order_by('email')


class InvalidEmailList(ListView):
    model = Voter
    paginate_by = 10
    queryset = Voter.objects.filter(invalid=True, email_confirmed=False).order_by('email')

    def get_context_data(self, **kwargs):
        context = super(InvalidEmailList, self).get_context_data(**kwargs)
        context['page_url_invalid_tag'] = '/voter/invalid/'
        return context

class IPVoterAction(ListView):

    def get(self, request, *args, **kwargs):
        # print(request.GET['ip'])
        return render(request, 'upstaged_data/ip_voter_list.html')

    def post(self, request, *args, **kwargs):
        # print(request.POST['v_action'])
        # print(request.POST['voter_email'])
        # messages.warning(request, 'Test message')
        if request.POST['v_action'] == 'valid':
            valid_act = True
            invalid_act = False
        if request.POST['v_action'] == 'invalid':
            valid_act = False
            invalid_act = True
        action_source = 'by User - '+str(request.user.email)
        # print(action_source)
        # print(valid_act)
        # print(invalid_act)
        Voter.objects.filter(email=request.POST['voter_email']).update(email_confirmed=valid_act, invalid=invalid_act, verification_pending=False, email_verification_source=action_source)
        return redirect('upstaged_data:ip-address-list')

class IPVoterList(ListView):
    template_name = 'upstaged_data/ip_voter_list.html'
    model = Datasheet

templates/upstaged_data/temp_ip_address_list.html
{% extends "layouts/base.html" %}

{% block title %} Data-sheet {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">TEmp IP Data Sheet</h5>
                            <div>
                                <form method="POST" >
                                    {% csrf_token %}
                                    <input type="text" name='num'/>
                                    <input type="submit"/>
                                </form>
                            </div>
                            <div>
                                <form method="POST" action="{% url 'upstaged_data:make-invalid-ip-voter' %}">
                                    {% csrf_token %}
                                    <input type="text" name='ip'/>
                                    <input type="submit" value="Make Invalid ( action on pending )">
                                </form>
                            </div>

                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Tables</a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Basic Tables</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Hover-table ] start -->
                    <div class="col-xl-12">
                        
                        <div class="card">
                     
                            <div class="card-block table-border-style">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                
                                                <th>Serial No</th>
                                                <th>IP</th>
                                                <th>Count</th>
                                                <th>Action</th>
              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for obj in object_list %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ obj.ip_address }}</td>
                                                    <td>{{ obj.ip_address__count }}</td>
                                                    <td>
                                                        <form method="POST" action="{% url 'upstaged_data:temp-ip-address-voters' %}">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="ip" value="{{ obj.ip_address }}"/>
                                                            <input type="submit" value="View Details"/>
                                                        </form>
                                                    </td>


                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>

                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Hover-table ] end -->

                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

templates/upstaged_data/test.html
<h1>Uploaded</h1>

templates/upstaged_data/voter_list.html
{% extends "layouts/base.html" %}

{% block title %} Emails {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<script>
    page_url_invalid_tag  = '{{page_url_invalid_tag}}';
</script>
{% endblock stylesheets %}

{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Voter List</h5>
                            <!-- {{fromDate}}
                            {{toDate}} -->
                            <a class="btn btn-danger float-right" href="{% url 'upstaged_data:all-invalid-emails' %}">Invalid Emails</a>
                            <a class="btn btn-success float-right" href="{% url 'upstaged_data:all-verified-emails' %}">Valid Emails</a>
                            <a class="btn btn-warning float-right" href="{% url 'upstaged_data:all-pending-emails' %}">Pending Verification</a>
                            {% if user.is_superuser %}
                            <a class="btn btn-info float-right" href="{% url 'upstaged_data:verification-emails-list' %}">Send Emails</a>
                            <a class="btn btn-info float-right" href="{% url 'upstaged_data:send_bulk-email' %}">Send Bulk Email</a>
                            {% endif %}

                            <a class="btn btn-primary float-right" href="{% url 'upstaged_data:unique-emails' %}">All Emails</a>
                            <a class="btn btn-primary float-right" href="{% url 'upstaged_data:export-voters' %}">Export</a>
                            
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Tables</a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Basic Tables</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Hover-table ] start -->
                    <div class="col-xl-12">
                        
                        <div class="card">
                            <div class="card-header">
                                {# .... **Now the pagination section** .... #}
                                {% if is_paginated %}
                                    <nav aria-label="Page navigation example float-right">
                                        <ul class="pagination">
                                            {% if page_obj.has_previous %}
                                                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                            {% endif %}

                                            {% if page_obj.number > 3 %}
                                            <li><a class="page-link" href="?page={{ page_obj.number|add:-3}}">{{ page_obj.number|add:-3 }}</a></li>
                                            {% endif %}
                                            {% if page_obj.number > 2  %}

                                            <li><a class="page-link" href="?page={{ page_obj.number|add:-2}}">{{ page_obj.number|add:-2 }}</a></li>
                                            {% endif %}
                                            {% if page_obj.number > 1 %}
                                            <li><a class="page-link" href="?page={{ page_obj.number|add:-1}}">{{ page_obj.number|add:-1 }}</a></li>
                                            {% endif %}

                                            {% for i in paginator.page_range %}

                                            {% if page_obj.number == i %}
                                            <li class="active page-link"><span>{{ i }} (current)</span></li>
                                            {% else %}
                                              <!-- <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li> -->
                                            {% endif %}
                                            {% endfor %}


                                            <span class="page-current">
                                                <!-- <li class="page-item"><a class="page-link" href="#!">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li> -->
                                            </span>
                                            {% if page_obj.has_next %}
                                                <li><a class="page-link" href="?page={{ page_obj.number|add:1}}">{{ page_obj.number|add:1 }}</a></li>
                                                <li><a class="page-link" href="?page={{ page_obj.number|add:2}}">{{ page_obj.number|add:2 }}</a></li>
                                                <li><a class="page-link" href="?page={{ page_obj.number|add:3}}">{{ page_obj.number|add:3 }}</a></li>
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                {% endif %}
                                <!-- {% ifequal request.get_full_path page_url_invalid_tag %}
                                    <a class="btn btn-info float-right" href="#">Export Invalid Data</a>
                                {% else %}
                                    <span>.</span>
                                {% endifequal %} -->

                                {% if user.is_superuser %}
                                    <a class="btn btn-dark float-right" href="{% url 'upstaged_data:email-load' %}">Load data</a>
                                {% endif %}
                            </div>
                            
                            <div class="card-block table-border-style">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Serial</th>
                                                <th>Title</th>
                                                <th>Email</th>
                                                <th>Updated at</th>
                                                <th>Email Confirmed</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for user in object_list %}
                                                <tr>
                                                    <td>{{forloop.counter0|add:page_obj.start_index }} </td>
                                                    <td>{{ user.name }}</td>
                                                    <td>{{ user.email }}</td>
                                                    <td>{{ user.updated_at }}</td>
                                                    <td>
                                                        {% if user.email_confirmed %}
                                                            <i class="fas fa-circle text-c-green f-10 m-r-15"></i>
                                                            <span class="text-success">{{ user.email_confirmed }}</span>
                                                        {% else %}
                                                            <i class="fas fa-circle text-c-red f-10 m-r-15"></i>
                                                            <span class="text-danger">{{ user.email_confirmed }}</span>
                                                        {% endif %}
                                                    </td>

                                                    <td>
                                                        {% if user.email_confirmed %}
                                                            <span class="text-success">Valid Email</span>
                                                        {% elif user.verification_pending and user.is_email_sent  %}
                                                            <span class="text-warning">Verification Pending / Verificaiton email sent</a>
                                                        {% elif user.invalid %}
                                                            <span class="text-c-red">Invalid email</a>
                                                        {% else %}
                                                            <span class="text-warning">Verification Pending</a>
                                                            <a class="label theme-bg text-white f-12" href="{% url 'upstaged_data:send_email_cnfrm' user.id %}">Send Activation Email</a>
                                                        {% endif%}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>

                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Hover-table ] end -->

                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}