accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, 
    PasswordResetConfirmView, PasswordResetCompleteView,
    LogoutView
)

from .forms import EmailValidationOnForgotPassword, PasswordResetConfirmForm
from .views import LoginView, RegisterView, ForgetPasswordView, ChangePasswordView
from .import views

app_name = 'accounts'

urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),

    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    re_path(r'^email-activate/(?P<oidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.email_activate, name='email_activate'),
    

    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'), 

    
    # path('password/reset/', ForgetPasswordView.as_view(), name='forget_password'),
    path('password/change/', ChangePasswordView.as_view(), name='change_password'),


    path('password/reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html',
            form_class=EmailValidationOnForgotPassword,
            html_email_template_name = 'accounts/email/forget_password_email.html'
            ), 
        name='password_reset'
        ),

    path('password/reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'), name='password_reset_done'),

    path('password/reset/confirm/<uidb64>[0-9A-Za-z]+)-<token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            form_class=PasswordResetConfirmForm), 
            name='password_reset_confirm'
        ),

    path('password/reset/complete/', 
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'),
            name='password_reset_complete'
        ),
    
]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
	
	path('voter-detail/<int:pk>/', views.voter_detail, name='voter-detail'),
	path('voter-react/', views.voter, name='voter-react' ),
	path('voter-create/', views.voter_react_create, name='create-voter'),
	path('vote-register/', views.vote_register, name='vote-register'),
	path('verifier/email/<str:email>', views.get_email_verify, name='email-verifier'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from accounts.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', TemplateView.as_view(template_name='homepage.html'), name='home'),
    path('', include('memail.urls')),
    path('', include('upstaged_data.urls')),

    path('', include('dashboard.urls')),
    path('', include('contacts.urls')),
    path('api-v1/', include('api.urls')),


    # path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

dashboard/urls.py
from django.urls import path

from dashboard.views import Dashboard, TestDashboard

from django.views.generic import TemplateView
from dashboard.views import date_wise_vote_list, redirect_dashboard_link
from django.contrib.auth.decorators import login_required


app_name = 'dashboard'

urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard/home.html'), name='home'),
    path('dashboard/', redirect_dashboard_link, name='dashboard'),
    path('voting/dashboard/', login_required(Dashboard.as_view()), name='voting-dashboard'),
    path('voting/dashboard/test/', login_required(TestDashboard.as_view()), name='test-voting-dashboard'),
    path('votes/date-wise/', login_required(date_wise_vote_list), name='date-wise-votes'),

    path('thank-you/', TemplateView.as_view(template_name='dashboard/thank-you.html'), name='thank-you'),

]

memail/urls.py
from django.urls import path
from django.conf.urls import url
from .import views
from memail.views import SimpleEmailView

app_name = 'memail'

urlpatterns = [
    path('memail/', SimpleEmailView.as_view(), name='email'),

    url(r'^image_load/$', views.image_load, name='image_load'),
    # path('image_load/', views.image_load, name='image_load'),

]

upstaged_data/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from upstaged_data.views import (
    EmailUpload, 
    VoterList, 
    send_email_confirmation, 
    VerifiedEmailList, 
    DateWiseEmailList, 
    DataSheetUpload, 
    PendingEmailList,
    InvalidEmailList,
    DataSheetListView,
    load_unique_emails,
    IsEmailSendList,
    IPAddressList,
    ip_address_list,
    link_voter_datasheet,
    send_bulk_email_confirmation,
    IPVoterList,
    export_voters_data,
    IPVoterAction,
    DuplicateDataSheetFind,
    DuplicateVoteList,
    export_dulicate_entry,
    TempIPAddressList,
    TempIPVoterAction,
    TempIPVoterList,
    make_invalid_action_for_ip_voters,
)


app_name = 'upstaged_data'

urlpatterns = [

    path('data-sheet/upload/', login_required(DataSheetUpload.as_view()), name="data-sheet-upload"),
    path('data-sheet/upload/duplicate/', login_required(DuplicateDataSheetFind.as_view()), name="find-duplicates"),

    path('data-sheet/email/load/', login_required(load_unique_emails), name="email-load"),
    path('data-sheet/email/bulk-send/', login_required(send_bulk_email_confirmation), name="send_bulk-email"),


    path('data-sheet/email/load/', login_required(link_voter_datasheet), name="link-voter-datasheet"),

    path('voter/duplicate/votes/', login_required(DuplicateVoteList.as_view()), name='duplicate-vote-list'),
    path('voter/duplicate/votes/export/', login_required(export_dulicate_entry), name='export-duplicate-vote-list'),

    path('voter/', login_required(VoterList.as_view()), name='unique-emails'),
    path('voter/verified/', login_required(VerifiedEmailList.as_view()), name='all-verified-emails'),
    path('voter/pending/', login_required(PendingEmailList.as_view()), name='all-pending-emails'),
    path('voter/invalid/', login_required(InvalidEmailList.as_view()), name='all-invalid-emails'),
    path('voter/verification/email/', login_required(IsEmailSendList.as_view()), name='verification-emails-list'),

    path('voter/ip-address/', login_required(IPAddressList.as_view()), name='ip-address-list'),
    path('voter/ip-address/voter/', login_required(IPVoterList.as_view()), name='ip-address-voters'),
    path('voter/ip-address/voter/action/', login_required(IPVoterAction.as_view()), name='ip-voters-action'),

    path('voter/ip-address/test/', login_required(TempIPAddressList.as_view()), name='temp-ip-address-list'),
    path('voter/ip-address/voter/test/', login_required(TempIPVoterList.as_view()), name='temp-ip-address-voters'),
    path('voter/ip-address/voter/action/test/', login_required(TempIPVoterAction.as_view()), name='temp-ip-voters-action'),
    path('voter/ip-address/voter/action/test/invalid/', login_required(make_invalid_action_for_ip_voters), name='make-invalid-ip-voter'),





    path('voter/export/', login_required(export_voters_data), name='export-voters'),

    # path('email/voter/ip-address/', ip_address_list, name='ip-address-list'),

    path('data-sheet/', login_required(DataSheetListView.as_view()), name='data-sheet'),

    path('email/user/date/', login_required(DateWiseEmailList.as_view()), name='date-wise-emails'),
    path('send-email-confirmation-link/<int:pk>/', login_required(send_email_confirmation), name='send_email_cnfrm'),



]

templates/includes/navigation copy.html
    <nav class="pcoded-navbar">
        <div class="navbar-wrapper">
            <div class="navbar-brand header-logo">
                <a target="_blank" href="#" class="b-brand">
                    <div class="b-bg">
                        <i class="feather icon-trending-up"></i>
                    </div>
                    <span class="b-title">CRM</span>
                    <span class="b-title">CRM</span>
                </a>
                <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
            </div>
            <div class="navbar-content scroll-div">
                <ul class="nav pcoded-inner-navbar">
                    <li class="nav-item pcoded-menu-caption">
                        <label>Navigation</label>
                    </li>
                    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                        class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
                            <span class="pcoded-mtext">Dashboard</span></a>
                    </li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>UI Element</label>
                    </li>
                    <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
                        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Components</span></a>
                        <ul class="pcoded-submenu">
                            <li class=""><a href="/ui-button.html" class="">Button</a></li>
                            <li class=""><a href="/ui-badges.html" class="">Badges</a></li>
                            <li class=""><a href="{/ui-breadcrumb-pagination.html}" class="">Breadcrumb & paggination</a></li>
                            <li class=""><a href="/ui-collapse.html" class="">Collapse</a></li>
                            <li class=""><a href="/ui-tabs.html" class="">Tabs & pills</a></li>
                            <li class=""><a href="/ui-typography.html" class="">Typography</a></li>


                            <li class=""><a href="/ui-icons.html" class="">Feather<span class="pcoded-badge label label-danger">NEW</span></a></li>
                        </ul>
                    </li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>Forms & table</label>
                    </li>
                    <li data-username="form elements advance componant validation masking wizard picker select" 
                        class="nav-item {% if 'forms' in segment %} active {% endif %}">
                        <a href="/ui-forms.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Form elements</span></a>
                    </li>
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="/ui-tables.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                    </li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>Chart & Maps</label>
                    </li>
                    <li data-username="Charts Morris" 
                        class="nav-item {% if 'charts-morris' in segment %} active {% endif %}">
                        <a href="/charts-morris.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a></li>
                    <li data-username="Maps Google" 
                        class="nav-item {% if 'maps-google' in segment %} active {% endif %}">
                        <a href="/maps-google.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span class="pcoded-mtext">Maps</span></a></li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>Pages</label>
                    </li>
                    <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe" class="nav-item pcoded-hasmenu">
                        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
                        <ul class="pcoded-submenu">
                            <li class=""><a href="/auth-reset-pass.html" class="">Reset Pass</a></li>
                            <li class=""><a href={% url 'register' %} class="">Register</a></li>
                        </ul>
                    </li>
                    <li data-username="Sample Page" 
                        class="nav-item {% if 'page-blank' in segment %} active {% endif %}">
                        <a href="/page-blank.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a></li>

                    <li data-username="Disabled Menu" class="nav-item">
                        <a href={% url 'logout' %} class="nav-link">
                            <span class="pcoded-micon">
                                <i class="feather icon-power"></i>
                            </span>
                            <span class="pcoded-mtext">Logout - [ {{ request.user.username }} ]</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

templates/includes/navigation.html
    <nav class="pcoded-navbar">
        <div class="navbar-wrapper">
            <div class="navbar-brand header-logo">
                <a href="/dashboard/" class="b-brand">
                    <div class="b-bg">
                        <i class="feather icon-trending-up"></i>
                    </div>
                    <span class="b-title">CRM (Voting)</span>
                </a>
                <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
            </div>
            <div class="navbar-content scroll-div">
                <ul class="nav pcoded-inner-navbar">
                    <li class="nav-item pcoded-menu-caption">
                        <label>Navigation</label>
                    </li>
                    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                        class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="{% url 'dashboard:voting-dashboard' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
                            <span class="pcoded-mtext">Dashboard</span></a>
                    </li>
                    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                        class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="{% url 'dashboard:test-voting-dashboard' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
                            <span class="pcoded-mtext">Test Dashboard</span></a>
                    </li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>Forms & table</label>
                    </li>
                    {% if user.is_active and user.is_superuser  %}

                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:data-sheet-upload' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Data-Sheet Upload</span></a>
                    </li>
                    <!-- <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'memail:email' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Send Email</span></a>
                    </li> -->
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:find-duplicates' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Duplicate Votes - Sheet upload</span></a>
                    </li>
                    {% endif %}
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:unique-emails' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Voters</span></a>
                    </li>
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:ip-address-list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">IP Address</span></a>
                    </li>
                    
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:duplicate-vote-list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Duplicate Votes</span></a>
                    </li>
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:data-sheet' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Data Sheet-Copy</span></a>
                    </li>
                    {% if user.is_active and user.is_staff  %}

                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="/admin/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Go to admin</span></a>
                    </li>
                    {% endif %}
                    {% if request.user.email %}
                    <li data-username="Disabled Menu" class="nav-item">
                        <a href="{% url 'accounts:logout' %}" class="nav-link">
                            <span class="pcoded-micon">
                                <i class="feather icon-power"></i>
                            </span>
                            <span class="pcoded-mtext">Logout - [ {{ request.user.first_name }} ]</span>
                        </a>
                    </li>
                    {% endif %}
                    <hr><hr>
                    <li data-username="Table bootstrap datatable footable" 
                        class="nav-item {% if 'tables' in segment %} active {% endif %}">
                        <a href="{% url 'upstaged_data:temp-ip-address-list' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">IP Address - Test</span></a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>

templates/includes/scripts.html
    <!-- Required Js -->
    <script src="/static/assets/js/vendor-all.min.js"></script>
    <script src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.min.js"></script>