api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
	
	path('voter-detail/<int:pk>/', views.voter_detail, name='voter-detail'),
	path('voter-react/', views.voter, name='voter-react' ),
	path('voter-create/', views.voter_react_create, name='create-voter'),
	path('vote-register/', views.vote_register, name='vote-register'),
	path('verifier/email/<str:email>', views.get_email_verify, name='email-verifier'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from accounts.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', TemplateView.as_view(template_name='homepage.html'), name='home'),
    path('', include('memail.urls')),
    path('', include('upstaged_data.urls')),

    path('', include('dashboard.urls')),
    path('', include('contacts.urls')),
    path('api-v1/', include('api.urls')),


    # path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

import_export/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from import_export.views import (
    EmailUpload, 
    EmailDumpList, 
    send_email_confirmation, 
    VerifiedEmailList, 
    DateWiseEmailList, 
    DataSheetUpload, 
    PendingEmailList,
    InvalidEmailList,
    DataSheetListView,
    load_unique_emails,
    IsEmailSendList,
    # IPAddressList,
    ip_address_list,
)


app_name = 'import_export'

urlpatterns = [

    path('data-sheet/upload/', DataSheetUpload.as_view(), name="data-sheet-upload"),

    path('data-sheet/email/load/', load_unique_emails, name="email-load"),

    path('email/voter/', EmailDumpList.as_view(), name='unique-emails'),
    path('email/voter/verified/', VerifiedEmailList.as_view(), name='all-verified-emails'),
    path('email/voter/pending/', PendingEmailList.as_view(), name='all-pending-emails'),
    path('email/voter/invalid/', InvalidEmailList.as_view(), name='all-invalid-emails'),
    path('email/voter/verification/email/', IsEmailSendList.as_view(), name='verification-emails-list'),

    # path('email/voter/ip-address/', IPAddressList.as_view(), name='ip-address-list'),

    path('email/voter/ip-address/', ip_address_list, name='ip-address-list'),

    path('data-sheet/', DataSheetListView.as_view(), name='data-sheet'),

    path('email/user/date/', DateWiseEmailList.as_view(), name='date-wise-emails'),
    path('send-email-confirmation-link/<int:pk>/', send_email_confirmation, name='send_email_cnfrm'),


]

import_export/models.py
from django.db import models
# Create your models here.



class Email_Dump(models.Model):
    name = models.CharField(max_length=50)
    email = models.TextField(unique=True)
    invalid = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)
    verification_pending = models.BooleanField(default=True)
    is_email_sent = models.BooleanField(default=False)
    email_sent = models.IntegerField(default=0)
    email_verification_source = models.CharField(max_length=100, default='Not Yet')
    vote_time = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']

    

class DataSheetFromCommonNinja(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    ip_address = models.TextField()
    group = models.CharField(max_length=50)
    round = models.CharField(max_length=50)
    game = models.CharField(max_length=5)
    voted_for = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']

import_export/views.py
import csv, io
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse

from django.views.generic import FormView, ListView
# Create your views here.
# one parameter named request
from import_export.models import  Email_Dump, DataSheetFromCommonNinja
from accounts.views import send_email_confirmation_link

from datetime import datetime
from django.utils.timezone import make_aware
from django.db.models import Count


class EmailUpload(FormView):

    def get(self, request, *args, **kwargs):
        """
        docstring
        """
        return render(request, 'import_export/emails_upload.html')

    def post(self, request, *args, **kwargs):
        """
        docstring
        """
        csv_file = request.FILES['file']
        # let's check if it is a csv file
        
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'THIS IS NOT A CSV FILE')  

        data_set = csv_file.read().decode('UTF-8')
        # setup a stream which is when we loop through each line we are able to handle a data in a stream
        io_string = io.StringIO(data_set)
        next(io_string)
        count = 0


        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            count = count + 1
            str_date = column[7].strip('GMT+0000 (Coordinated Universal Time)')

            try:
                # str_date = "Nov 23 2020 16:19:41" # example
                date_time_obj = datetime.strptime(str_date, "%b %d %Y %H:%M:%S")
                # date_time_obj = "2012-09-04 06:00Z" # example
            except ValueError as e:
                date_time_obj = datetime.strptime(str_date, "%b %d %Y %H:%M:")

            _, created = Email_Dump.objects.update_or_create(
                name=column[0],
                email=column[1],
                vote_time=date_time_obj,
            )
            print(count)

        messages.warning(request, 'message from post function')
        return render(request, 'import_export/emails_upload.html')

# Data Sheet upload - form
class DataSheetUpload(FormView):

    def get(self, request, *args, **kwargs):
        """
        docstring
        """
        return render(request, 'import_export/data_sheet_upload.html')

    def post(self, request, *args, **kwargs):
        """
        docstring
        """
        csv_file = request.FILES['file']
        # let's check if it is a csv file
        
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'THIS IS NOT A CSV FILE')  

        data_set = csv_file.read().decode('UTF-8')
        # setup a stream which is when we loop through each line we are able to handle a data in a stream
        io_string = io.StringIO(data_set)
        next(io_string)
        count = 0
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            count = count + 1
            
            _, created = DataSheetFromCommonNinja.objects.update_or_create(
                name=column[0],
                email=column[1],
                ip_address = column[2], 
                group = column[3], 
                round = column[4], 
                game = column[5],
                voted_for = column[6],
            )
            print(count)

        messages.warning(request, 'message from post function')
        return render(request, 'import_export/data_sheet_upload.html')



# Unique / Email Voter listing
class EmailDumpList(ListView):
    model = Email_Dump
    paginate_by = 10
    queryset = Email_Dump.objects.all()

class VerifiedEmailList(ListView):
    model = Email_Dump
    paginate_by = 10
    queryset = Email_Dump.objects.filter(email_confirmed=True).order_by('email')


class PendingEmailList(ListView):
    model = Email_Dump
    paginate_by = 10
    queryset = Email_Dump.objects.filter(verification_pending=True, email_confirmed=False, invalid=False).order_by('email')

class IsEmailSendList(ListView):
    model = Email_Dump
    paginate_by = 10
    queryset = Email_Dump.objects.filter(verification_pending=True, email_confirmed=False, invalid=False, is_email_sent=False).order_by('email')


class InvalidEmailList(ListView):
    model = Email_Dump
    paginate_by = 10
    queryset = Email_Dump.objects.filter(invalid=True, email_confirmed=False).order_by('email')


# IP Address - linting
# class IPAddressList(ListView):
#     template_name = 'ip_address_list.html'
#     model = DataSheetFromCommonNinja
#     queryset = DataSheetFromCommonNinja.objects.values('ip_address').order_by('ip_address').annotate(the_count=Count('ip_address'))

def ip_address_list(request):
    ip_list = list(DataSheetFromCommonNinja.objects.values("ip_address").order_by('the_count').annotate(the_count=Count('ip_address')))
    # ip_list = [{'ip_address': '100.1.131.190', 'the_count': 4}, {'ip_address': '100.12.91.148', 'the_count': 4},]
    return render(request, 'import_export/ip_address_list.html', context={'object_list': ip_list})

# Data Sheet Copy - linting
class DataSheetListView(ListView):
    model = DataSheetFromCommonNinja
    paginate_by = 10
    queryset = DataSheetFromCommonNinja.objects.all().order_by('name')



def load_unique_emails(request):
    # uni_email_obj = list(DataSheetFromCommonNinja.objects.order_by().values('name', 'email').distinct())
    # uni_email_obj = DataSheetFromCommonNinja.objects.order_by().values( 'email').distinct().count()
    # uni_email_obj = DataSheetFromCommonNinja.objects.values_list('email').distinct()
    uni_email_obj = list(DataSheetFromCommonNinja.objects.all().order_by('email').distinct('email'))


    # print(uni_email_obj)
    
    count = 0
    new_entry = 0
    for uobj in uni_email_obj:
        count = count +1
        # if Email_Dump.objects.get(email=uobj.email):
        #     print('exist')
        # else:
        #     Email_Dump.objects.create(name=uobj.name, email=uobj.email).save()
        #     print('exist')


        _, created = Email_Dump.objects.update_or_create(
            name=uobj.name,
            email=uobj.email)
        print(count)
        if created:
            new_entry = new_entry +1
    
    str_msg = 'New entry '+ str(new_entry)
    messages.success(request, str_msg)
    return redirect('import_export:unique-emails')


class DateWiseEmailList(ListView):
    model = Email_Dump
    paginate_by = 10
    
    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.") % {
                    'class_name': self.__class__.__name__,
                })
        fromDate = request.GET['fromDate']
        toDate = request.GET['toDate']
        
        context = self.get_context_data(fromDate=fromDate, toDate=toDate)
        return self.render_to_response(context)

    def get_context_data(self, *, object_list=None, fromDate, toDate,  **kwargs):
        """Get the context for this view."""

        context = {
            'fromDate': fromDate,
            'toDate': toDate,

        }
        
        context.update(kwargs)
        return super().get_context_data(**context)

    

    
def send_email_confirmation(request, pk):
    obj = Email_Dump.objects.get(pk=pk)
    result = send_email_confirmation_link(request, obj, obj.email)
    if result:
        return redirect('import_export:unique-emails')
    
    return redirect('import_export:unique-emails')

templates/import_export/datasheetfromcommonninja_list.html
{% extends "layouts/base.html" %}

{% block title %} Data-sheet {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Data Sheet</h5>
                            <!-- {{fromDate}}
                            {{toDate}}
                            <form method="GET" action="{% url 'import_export:date-wise-emails' %}">
                               {% csrf_token %}
                                <label for="from">From</label>
                                <input type="text" id="from" name="fromDate">
                                <label for="to">to</label>
                                <input type="text" id="to" name="toDate">
                                <input type="submit" id="date-sub-btn"/>
                            </form> -->

                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Tables</a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Basic Tables</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Hover-table ] start -->
                    <div class="col-xl-12">
                        
                        <div class="card">
                            <div class="card-header">
                                {# .... **Now the pagination section** .... #}
                                {% if is_paginated %}
                                    <nav aria-label="Page navigation example float-right">
                                        <ul class="pagination">
                                            {% if page_obj.has_previous %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                            {% endif %}
                                            <span class="page-current">
                                                <li class="page-item"><a class="page-link" href="#!">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                                            </span>
                                            {% if page_obj.has_next %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                {% endif %}
                            </div>
                            
                            <div class="card-block table-border-style">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                
                                                <th>Serial</th>
                                                <th>Title</th>
                                                <th>Email</th>
                                                <th>Round</th>
                                                <th>Game</th>
              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for user in object_list %}
                                                <tr>
                                                    <td>{{forloop.counter0|add:page_obj.start_index }} </td>
                                                    <td>{{ user.name }}</td>
                                                    <td>{{ user.email }}</td>
                                                    <td>{{ user.round }}</td>
                                                    <td>{{ user.game }}</td>


                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>

                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Hover-table ] end -->

                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    var dateFormat = "mm/dd/yy",
      from = $( "#from" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 3
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#to" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 3
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });
 
    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }
 
      return date;
    }
  } );
  </script>
{% endblock javascripts %}

templates/import_export/email_dump_list.html
{% extends "layouts/base.html" %}

{% block title %} Emails {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Unique Email / Voter</h5>
                            <!-- {{fromDate}}
                            {{toDate}} -->
                            <a class="btn btn-danger float-right" href="{% url 'import_export:all-invalid-emails' %}">Invalid Emails</a>
                            <a class="btn btn-success float-right" href="{% url 'import_export:all-verified-emails' %}">Valid Emails</a>
                            <a class="btn btn-warning float-right" href="{% url 'import_export:all-pending-emails' %}">Pending Verification</a>
                            <a class="btn btn-info float-right" href="{% url 'import_export:verification-emails-list' %}">Send Emails</a>
                            <a class="btn btn-primary float-right" href="{% url 'import_export:unique-emails' %}">All Emails</a>
                            <!-- <form method="GET" action="{% url 'import_export:date-wise-emails' %}">
                               {% csrf_token %}
                                <label for="from">From</label>
                                <input type="text" id="from" name="fromDate">
                                <label for="to">to</label>
                                <input type="text" id="to" name="toDate">
                                <input type="submit" id="date-sub-btn"/>
                            </form> -->
                            
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Tables</a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Basic Tables</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Hover-table ] start -->
                    <div class="col-xl-12">
                        
                        <div class="card">
                            <div class="card-header">
                                {# .... **Now the pagination section** .... #}
                                {% if is_paginated %}
                                    <nav aria-label="Page navigation example float-right">
                                        <ul class="pagination">
                                            {% if page_obj.has_previous %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                            {% endif %}
                                            {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                              <li class="active page-link"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                            {% else %}
                                              <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                            {% endfor %}
                                            <span class="page-current">
                                                <li class="page-item"><a class="page-link" href="#!">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                                            </span>
                                            {% if page_obj.has_next %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                {% endif %}
                                <a class="btn btn-dark float-right" href="{% url 'import_export:email-load' %}">Load data</a>

                            </div>
                            
                            <div class="card-block table-border-style">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Serial</th>
                                                <th>Title</th>
                                                <th>Email</th>
                                                <th>Updated at</th>
                                                <th>Email Confirmed</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for user in object_list %}
                                                <tr>
                                                    <td>{{forloop.counter0|add:page_obj.start_index }} </td>
                                                    <td>{{ user.name }}</td>
                                                    <td>{{ user.email }}</td>
                                                    <td>{{ user.updated_at }}</td>
                                                    <td>
                                                        {% if user.email_confirmed %}
                                                            <i class="fas fa-circle text-c-green f-10 m-r-15"></i>
                                                            <span class="text-success">{{ user.email_confirmed }}</span>
                                                        {% else %}
                                                            <i class="fas fa-circle text-c-red f-10 m-r-15"></i>
                                                            <span class="text-danger">{{ user.email_confirmed }}</span>
                                                        {% endif %}
                                                    </td>

                                                    <td>
                                                        {% if user.email_confirmed %}
                                                            <span class="text-success">Valid Email</span>
                                                        {% elif user.verification_pending and user.is_email_sent  %}
                                                            <span class="text-warning">Verification Pending / Verificaiton email sent</a>
                                                        {% elif user.invalid %}
                                                            <span class="text-c-red">Invalid email</a>
                                                        {% else %}
                                                            <span class="text-warning">Verification Pending</a>
                                                            <a class="label theme-bg text-white f-12" href="{% url 'import_export:send_email_cnfrm' user.id %}">Send Activation Email</a>
                                                        {% endif%}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>

                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Hover-table ] end -->

                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    var dateFormat = "mm/dd/yy",
      from = $( "#from" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 3
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#to" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 3
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });
 
    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }
 
      return date;
    }
  } );
  </script>
{% endblock javascripts %}