api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
	
	path('voter-detail/<int:pk>/', views.voter_detail, name='voter-detail'),
	path('voter-react/', views.voter, name='voter-react' ),
	path('voter-create/', views.voter_react_create, name='create-voter'),
	path('vote-register/', views.vote_register, name='vote-register'),
	path('verifier/email/<str:email>', views.get_email_verify, name='email-verifier'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from accounts.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', TemplateView.as_view(template_name='homepage.html'), name='home'),
    path('', include('memail.urls')),
    path('', include('upstaged_data.urls')),

    path('', include('dashboard.urls')),
    path('', include('contacts.urls')),
    path('api-v1/', include('api.urls')),


    # path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

dashboard/urls.py
from django.urls import path

from dashboard.views import Dashboard, TestDashboard

from django.views.generic import TemplateView
from dashboard.views import date_wise_vote_list, redirect_dashboard_link
from django.contrib.auth.decorators import login_required


app_name = 'dashboard'

urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard/home.html'), name='home'),
    path('dashboard/', redirect_dashboard_link, name='dashboard'),
    path('voting/dashboard/', login_required(Dashboard.as_view()), name='voting-dashboard'),
    path('voting/dashboard/test/', login_required(TestDashboard.as_view()), name='test-voting-dashboard'),
    path('votes/date-wise/', login_required(date_wise_vote_list), name='date-wise-votes'),

    path('thank-you/', TemplateView.as_view(template_name='dashboard/thank-you.html'), name='thank-you'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import View

from upstaged_data.models import Datasheet, Voter, DuplicateVotes, TempVoter
from django.db import connection, transaction
from datetime import date, timedelta, datetime

def find_valid_votes_team_wise(game_number, voted_for):

        try:
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN voter ON datasheet.email = voter.email "\
                    +"WHERE voter.email_confirmed=True "\
                        +"AND datasheet.game='%s' AND datasheet.voted_for='%s' AND datasheet.round='Semifinals'" % (game_number, voted_for))
            
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]
        except Exception as e:
            print(e) 
            pass


def find_invalid_votes_team_wise(game_number, voted_for):
        try:
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN voter ON datasheet.email = voter.email "\
                    +"WHERE voter.invalid=True "\
                        +"AND datasheet.game='%s' AND datasheet.voted_for='%s' AND datasheet.round='Semifinals'" % (game_number, voted_for))
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]
        except Exception as e:
            print(e)
            pass

def find_pending_votes_team_wise(game_number, voted_for):

        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN voter ON datasheet.email = voter.email "\
                    +"WHERE voter.verification_pending=True AND voter.email_confirmed=False AND voter.invalid=False "\
                        +"AND datasheet.game='%s' AND datasheet.voted_for='%s' AND datasheet.round='Semifinals'" % (game_number, voted_for))
            
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]
        except Exception as e:
            print(e)           
            pass

# temp ------
def temp_find_valid_votes_team_wise(game_number, voted_for):

        try:
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN temp_voter ON datasheet.email = temp_voter.email "\
                    +"WHERE temp_voter.email_confirmed=True "\
                        +"AND datasheet.game='%s' AND datasheet.voted_for='%s' AND datasheet.round='Semifinals'" % (game_number, voted_for))
            
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]
        except Exception as e:
            print(e) 
            pass


def temp_find_invalid_votes_team_wise(game_number, voted_for):
        try:
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN temp_voter ON datasheet.email = temp_voter.email "\
                    +"WHERE temp_voter.invalid=True "\
                        +"AND datasheet.game='%s' AND datasheet.voted_for='%s' AND datasheet.round='Semifinals'" % (game_number, voted_for))
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]
        except Exception as e:
            print(e)
            pass

def temp_find_pending_votes_team_wise(game_number, voted_for):

        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN temp_voter ON datasheet.email = temp_voter.email "\
                    +"WHERE temp_voter.verification_pending=True AND temp_voter.email_confirmed=False AND temp_voter.invalid=False "\
                        +"AND datasheet.game='%s' AND datasheet.voted_for='%s' AND datasheet.round='Semifinals'" % (game_number, voted_for))
            
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]
        except Exception as e:
            print(e)           
            pass

def temp_total_auth_votes():
        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN temp_voter ON datasheet.email = temp_voter.email "\
                    +"WHERE temp_voter.email_confirmed=True")
                        
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]

        except Exception as e:
            print(e) 
            pass

def temp_total_invalid_votes():
        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN temp_voter ON datasheet.email = temp_voter.email "\
                    +"WHERE temp_voter.invalid=True")
                        
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]

        except Exception as e:
            print(e) 
            pass
    

def temp_total_pending_votes():
        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN temp_voter ON datasheet.email = temp_voter.email "\
                    +"WHERE temp_voter.verification_pending=True")
                        
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]

        except Exception as e:
            print(e) 
            pass




# close temp

def total_auth_votes():
        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN voter ON datasheet.email = voter.email "\
                    +"WHERE voter.email_confirmed=True")
                        
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]

        except Exception as e:
            print(e) 
            pass

def total_invalid_votes():
        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN voter ON datasheet.email = voter.email "\
                    +"WHERE voter.invalid=True")
                        
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]

        except Exception as e:
            print(e) 
            pass
    

def total_pending_votes():
        try: 
            p = ("SELECT COUNT (*) FROM datasheet "\
                +"JOIN voter ON datasheet.email = voter.email "\
                    +"WHERE voter.verification_pending=True")
                        
            cursor = connection.cursor()
            cursor.execute(p)
            row = cursor.fetchone()
            return row[0]

        except Exception as e:
            print(e) 
            pass

def find_date_wise_votes(obj_list):
        try:
            date_wise_auth_votes = 0
            date_wise_dis_votes = 0
            date_wise_pending_votes = 0
            # ds_list = Datasheet.objects.filter(vote_time__contains=start_date)
            for ds in obj_list:
                if Voter.objects.get(email=ds.email):
                    vtr = Voter.objects.get(email=ds.email)
                    if vtr.email_confirmed:
                        date_wise_auth_votes = date_wise_auth_votes +1
                    if vtr.invalid:
                        date_wise_dis_votes = date_wise_dis_votes +1
                    if vtr.verification_pending:
                        date_wise_pending_votes = date_wise_pending_votes +1
                    
                else:
                    pass
            
            # print(date_wise_auth_votes)
            # print(date_wise_dis_votes)
            # print(date_wise_pending_votes)
            date_wise_total_votes = date_wise_auth_votes + date_wise_dis_votes + date_wise_pending_votes
            date_wise_vote_list =[date_wise_total_votes, date_wise_auth_votes, date_wise_dis_votes, date_wise_pending_votes,]

            return date_wise_vote_list
        except Exception as e:
            print(e) 
            pass

def dashboard_data():
    s = Datasheet.objects.latest('updated_at')
    total_voters = Voter.objects.all().count()
    auth_voters = Voter.objects.filter(email_confirmed=True).count()
    verification_pending = Voter.objects.filter(email_confirmed=False, verification_pending=True, invalid=False).count()
    invalid_voters = Voter.objects.filter(invalid=True).count()
    duplicates_votes = DuplicateVotes.objects.all().count()

    valid_vote_for_harvard = find_valid_votes_team_wise(game_number='25', voted_for='#2 Harvard - Opportunes')
    invalid_vote_for_harvard = find_invalid_votes_team_wise(game_number='25', voted_for='#2 Harvard - Opportunes')
    pending_vote_for_harvard = find_pending_votes_team_wise(game_number='25', voted_for='#2 Harvard - Opportunes')

    valid_vote_for_rutgers = find_valid_votes_team_wise(game_number='25', voted_for='#2 Rutgers - Raag')
    invalid_vote_for_rutgers = find_invalid_votes_team_wise(game_number='25', voted_for='#2 Rutgers - Raag')
    pending_vote_for_rutgers = find_pending_votes_team_wise(game_number='25', voted_for='#2 Rutgers - Raag')

    valid_vote_for_penn = find_valid_votes_team_wise(game_number='26', voted_for='#2 U Penn - Penn Masala')
    invalid_vote_for_penn = find_invalid_votes_team_wise(game_number='26', voted_for='#2 U Penn - Penn Masala')
    pending_vote_for_penn = find_pending_votes_team_wise(game_number='26', voted_for='#2 U Penn - Penn Masala')

    valid_vote_for_illinois = find_valid_votes_team_wise(game_number='26', voted_for='#2 U Illinois - No Comment')
    invalid_vote_for_illinois = find_invalid_votes_team_wise(game_number='26', voted_for='#2 U Illinois - No Comment')
    pending_vote_for_illinois = find_pending_votes_team_wise(game_number='26', voted_for='#2 U Illinois - No Comment')

templates/dashboard/date_wise_votes_list.html
{% extends "layouts/base.html" %}

{% block title %} Data-sheet {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
{% endblock stylesheets %}


{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Data Sheet</h5>
                            <!-- {{fromDate}}
                            {{toDate}} -->
                            <form method="POST" action="{% url 'dashboard:date-wise-votes' %}">
                               {% csrf_token %}
                                <label for="from">From</label>
                                <input type="text" id="from" name="dates"  value="11/20/2020 - 11/30/2020">

                                <input type="submit" id="date-sub-btn"/>
                            </form>

                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Tables</a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Basic Tables</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Hover-table ] start -->
                    <div class="col-xl-12">
                        
                        <div class="card">
                            <div class="card-header">
    
                            </div>
                            
                            <div class="card-block table-border-style">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                
                                                <th>Serial</th>
                                                <th>Title</th>
                                                <th>Email</th>
                                                <th>Round</th>
                                                <th>Game</th>
              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for obj in object_list %}
                                                <tr>
                                                    <td>{{forloop.counter }} </td>
                                                    <td>{{ obj.name }}</td>
                                                    <td>{{ obj.email }}</td>
                                                    <td>{{ obj.round }}</td>
                                                    <td>{{ obj.game }}</td>


                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>

                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Hover-table ] end -->

                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script> -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script>
  
    $('input[name="dates"]').daterangepicker();

</script>
{% endblock javascripts %}

templates/dashboard/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<p class="lead">
    <a href="{% url 'dashboard:voting-dashboard'%}" class="btn btn-lg btn-info" data-toggle="tooltip" data-placement="right" title="Click to enter">
        Bracket & Voting &nbsp; &nbsp;
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-index" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M6.75 1a.75.75 0 0 0-.75.75V9a.5.5 0 0 1-1 0v-.89l-1.003.2a.5.5 0 0 0-.399.546l.345 3.105a1.5 1.5 0 0 0 .243.666l1.433 2.15a.5.5 0 0 0 .416.223h6.385a.5.5 0 0 0 .434-.252l1.395-2.442a2.5 2.5 0 0 0 .317-.991l.272-2.715a1 1 0 0 0-.995-1.1H13.5v1a.5.5 0 0 1-1 0V7.154a4.208 4.208 0 0 0-.2-.26c-.187-.222-.368-.383-.486-.43-.124-.05-.392-.063-.708-.039a4.844 4.844 0 0 0-.106.01V8a.5.5 0 0 1-1 0V5.986c0-.167-.073-.272-.15-.314a1.657 1.657 0 0 0-.448-.182c-.179-.035-.5-.04-.816-.027l-.086.004V8a.5.5 0 0 1-1 0V1.75A.75.75 0 0 0 6.75 1zM8.5 4.466V1.75a1.75 1.75 0 0 0-3.5 0v5.34l-1.199.24a1.5 1.5 0 0 0-1.197 1.636l.345 3.106a2.5 2.5 0 0 0 .405 1.11l1.433 2.15A1.5 1.5 0 0 0 6.035 16h6.385a1.5 1.5 0 0 0 1.302-.756l1.395-2.441a3.5 3.5 0 0 0 .444-1.389l.272-2.715a2 2 0 0 0-1.99-2.199h-.582a5.184 5.184 0 0 0-.195-.248c-.191-.229-.51-.568-.88-.716-.364-.146-.846-.132-1.158-.108l-.132.012a1.26 1.26 0 0 0-.56-.642 2.634 2.634 0 0 0-.738-.288c-.31-.062-.739-.058-1.05-.046l-.048.002zm2.094 2.025z"/>
        </svg>
    </a>
</p>
<p class="lead">
    <a  href="#" class="btn btn-lg btn-secondary btn-disable" data-toggle="tooltip" data-placement="right" title="Coming Soon">Judges Stage</a>
</p>
<p class="lead">
    <a href="#" class="btn btn-lg btn-secondary btn-disable" data-toggle="tooltip" data-placement="right" title="Coming Soon">Participants Center</a>
</p>
<p class="lead">
    <a href="#" class="btn btn-lg btn-secondary btn-disable" data-toggle="tooltip" data-placement="right" title="Coming Soon">Audience Management</a>
</p>
<p class="lead">
    <a href="#" class="btn btn-lg btn-secondary btn-disable" data-toggle="tooltip" data-placement="right" title="Coming Soon">UEG Analytics</a>
</p>

{% endblock content %}

templates/dashboard/thank-you.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 403 Page {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather x-circle"></i>
                    </div>
                    <h3 class="mb-4">Voting is now closed.</h3>

                    <br />

                    <span class="mb-0 text-muted">
                        1FS & UpStaged Team
                    </span>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}